version: '3.8'
services:
  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./src/main/resources/locations.json:/docker-entrypoint-initdb.d/locations.json:ro
    environment:
      MONGO_INITDB_DATABASE: restaurantdb


volumes:
  mongodb_data: